services:
  img10:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - img10_uploads:/app/uploads
      - img10_thumbnails:/app/thumbnails
      - img10_database:/app/images.db
    networks:
      - app-network
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - img10
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  img10_uploads:
    driver: local
  img10_thumbnails:
    driver: local
  img10_database:
    driver: local
